import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('pmo-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('pmo-language', language);
    // Apply RTL for Arabic
    if (language === 'ar') {
      document.documentElement.setAttribute('dir', 'rtl');
      document.documentElement.setAttribute('lang', 'ar');
    } else {
      document.documentElement.setAttribute('dir', 'ltr');
      document.documentElement.setAttribute('lang', 'en');
    }
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.executive': 'Executive Overview',
    'nav.portfolio': 'Portfolio Deep Dive',
    'nav.project': 'Project Manager',
    'nav.details': 'Project Details',
    'nav.components': 'Components Library',
    
    // Executive Overview
    'exec.title': 'Executive Portfolio Overview',
    'exec.subtitle': 'Are we on track to deliver?',
    'exec.portfolioHealth': 'Portfolio Health',
    'exec.activeProjects': 'Active Projects',
    'exec.totalBudget': 'Total Budget',
    'exec.avgConfidence': 'Avg. Delivery Confidence',
    'exec.onTrack': 'On Track',
    'exec.atRisk': 'At Risk',
    'exec.critical': 'Critical',
    'exec.strategicAlignment': 'Strategic Alignment',
    'exec.deliveryTrend': 'Delivery Confidence Trend',
    'exec.topRisks': 'Top Portfolio Risks',
    'exec.budgetUtilization': 'Budget Utilization by Initiative',
    'exec.upcomingMilestones': 'Upcoming Critical Milestones',
    'exec.spi': 'Avg. SPI',
    'exec.cpi': 'Avg. CPI',
    'exec.projects': 'projects',
    'exec.spent': 'Spent',
    'exec.forecast': 'Forecast',
    'exec.overBudget': 'Over Budget',
    'exec.underBudget': 'Under Budget',
    'exec.variance': 'Variance',
    'exec.valueDelivery': 'Value Delivery',
    'exec.planned': 'Planned',
    'exec.delivered': 'Delivered',
    'exec.deliveryRate': 'Delivery Rate',
    'exec.initiatives': 'Initiatives',
    'exec.overBudgetProjects': 'Top 5 Over-Budget Projects',
    'exec.project': 'Project',
    'exec.pm': 'PM',
    'exec.dueDate': 'Due Date',
    'exec.owner': 'Owner',
    'exec.probability': 'Probability',
    'exec.impact': 'Impact',
    'exec.mitigation': 'Mitigation',
    'exec.activeFilters': 'Active Filters',
    'exec.clearAll': 'Clear All',
    'exec.month': 'Month',
    'exec.confidence': 'Confidence',
    'exec.target': 'Target',
    
    // Portfolio Deep Dive
    'portfolio.title': 'Portfolio Deep Dive',
    'portfolio.subtitle': 'Which projects are failing and why?',
    'portfolio.highRisk': 'High-Risk Projects',
    'portfolio.openRisks': 'Total Open Risks',
    'portfolio.overAllocated': 'Over-Allocated Roles',
    'portfolio.milestoneAdherence': 'Avg Milestone Adherence',
    'portfolio.performanceMatrix': 'Project Performance Matrix (SPI vs CPI)',
    'portfolio.comparisonMatrix': 'Multi-Project Comparison Matrix',
    'portfolio.riskConcentration': 'Risk Concentration (Impact × Probability)',
    'portfolio.riskTypeDistribution': 'Risk Type Distribution',
    'portfolio.resourceUtilization': 'Resource Utilization by Role',
    'portfolio.milestoneTrend': 'Milestone Adherence Trend',
    'portfolio.highRiskTable': 'High-Risk Projects (6+ Open Risks)',
    'portfolio.openIssues': 'Open Issues',
    'portfolio.6plusRisks': '6+ open risks each',
    'portfolio.acrossAll': 'Across all projects',
    'portfolio.resourceConstraints': 'Resource constraints',
    'portfolio.portfolioAvg': 'Portfolio average',
    'portfolio.bubbleSize': 'Bubble size = Budget | Color = Status | Quadrants: Top-right = Best Performance',
    'portfolio.investmentRisk': 'Investment at Risk: Budget vs Delivery Confidence | Bubble size = Open Risks | Bottom-right = High investment, low confidence',
    'portfolio.lowImpact': 'Low Impact',
    'portfolio.mediumImpact': 'Medium Impact',
    'portfolio.highImpact': 'High Impact',
    'portfolio.criticalImpact': 'Critical Impact',
    'portfolio.highProb': 'High',
    'portfolio.mediumProb': 'Medium',
    'portfolio.lowProb': 'Low',
    'portfolio.intensity': 'Intensity:',
    'portfolio.low': 'Low',
    'portfolio.medium': 'Medium',
    'portfolio.high': 'High',
    'portfolio.topRight': 'Higher values in top-right = More critical risks',
    'portfolio.capacity': 'Capacity',
    'portfolio.allocated': 'Allocated',
    'portfolio.overAllocation': 'Over-Allocation Alerts:',
    'portfolio.overCapacity': 'h over capacity',
    'portfolio.plannedMilestones': 'Planned Milestones',
    'portfolio.achievedMilestones': 'Achieved Milestones',
    'portfolio.forecastAccuracy': 'Forecast Accuracy',
    'portfolio.improvingTrend': 'Improving trend',
    'portfolio.avgDelay': 'Avg Milestone Delay',
    'portfolio.days': 'days',
    'portfolio.downFrom': 'Down from 6.5',
    'portfolio.highRiskZone': 'High Risk Zone',
    'portfolio.highRiskDesc': 'Budget > $15M, Confidence < 70%',
    'portfolio.avgRiskExposure': 'Avg Risk Exposure',
    'portfolio.risksPerProject': 'risks/project',
    'portfolio.highConfidence': 'High Confidence',
    'portfolio.confidence80': 'Confidence ≥ 80%',
    'portfolio.schedulePerformance': 'Schedule Performance Index (SPI)',
    'portfolio.costPerformance': 'Cost Performance Index (CPI)',
    'portfolio.projectBudget': 'Project Budget ($M)',
    'portfolio.deliveryConfidence': 'Delivery Confidence (%)',
    'portfolio.confidenceThreshold': '70% Confidence Threshold',
    
    // Project Manager View
    'pm.title': 'Project Manager View',
    'pm.subtitle': "What's blocking me this week?",
    'pm.weeklyFocus': 'Weekly Focus',
    'pm.schedulePerformance': 'Schedule Performance (EV vs PV)',
    'pm.costPerformance': 'Cost Performance',
    'pm.riskRegister': 'Risk Register',
    'pm.issueLog': 'Issue Log',
    'pm.resourceAllocation': 'Resource Allocation',
    'pm.tasksOverdue': 'Tasks Overdue',
    'pm.blockers': 'Active Blockers',
    'pm.teamVelocity': 'Team Velocity',
    'pm.sprintProgress': 'Sprint Progress',
    'pm.thisWeek': 'This Week',
    'pm.requiresAction': 'Requires action',
    'pm.needsResolution': 'Needs resolution',
    'pm.pointsPerSprint': 'points/sprint',
    'pm.stable': 'Stable',
    'pm.completed': 'Completed',
    'pm.remaining': 'Remaining',
    'pm.earnedValue': 'Earned Value (EV)',
    'pm.plannedValue': 'Planned Value (PV)',
    'pm.actualCost': 'Actual Cost (AC)',
    'pm.description': 'Description',
    'pm.assignee': 'Assignee',
    'pm.role': 'Role',
    'pm.allocation': 'Allocation',
    'pm.available': 'Available',
    'pm.overAllocated': 'Over-allocated',
    'pm.week': 'Week',
    
    // Project Details
    'details.title': 'Project Detail Drill-Down',
    'details.subtitle': 'Where are the bottlenecks?',
    'details.overview': 'Project Overview',
    'details.taskBreakdown': 'Task Breakdown by Phase',
    'details.criticalPath': 'Critical Path Analysis',
    'details.burndown': 'Sprint Burndown',
    'details.selectProject': 'Select a project to view details',
    'details.name': 'Project Name',
    'details.manager': 'Project Manager',
    'details.phase': 'Current Phase',
    'details.progress': 'Progress',
    'details.health': 'Health',
    'details.totalTasks': 'Total Tasks',
    'details.completedTasks': 'Completed',
    'details.inProgress': 'In Progress',
    'details.blocked': 'Blocked',
    'details.longestTask': 'Longest Task on Critical Path',
    'details.criticalTasks': 'Critical Tasks',
    'details.totalDuration': 'Total Duration',
    'details.atRiskTasks': 'At-Risk Tasks',
    'details.ideal': 'Ideal',
    'details.actual': 'Actual',
    'details.timeline': 'Timeline',
    'details.task': 'Task',
    'details.duration': 'Duration',
    'details.dependencies': 'Dependencies',
    'details.slack': 'Slack',
    'details.design': 'Design',
    'details.development': 'Development',
    'details.testing': 'Testing',
    'details.deployment': 'Deployment',
    'details.day': 'Day',
    'details.tasksRemaining': 'Tasks Remaining',
    
    // Common
    'common.status': 'Status',
    'common.budget': 'Budget',
    'common.confidence': 'Confidence',
    'common.risks': 'Risks',
    'common.issues': 'Issues',
    'common.view': 'View',
    'common.filters': 'Filters',
    'common.all': 'All',
    'common.search': 'Search projects...',
    'common.portfolio': 'Portfolio',
    'common.program': 'Program',
    'common.strategicInitiative': 'Strategic Initiative',
    'common.projectManager': 'Project Manager',
    'common.spi': 'SPI',
    'common.cpi': 'CPI',
    'common.projects': 'projects',
    
    // AI Assistant
    'ai.title': 'PMO AI Assistant',
    'ai.subtitle': 'Powered by Advanced Portfolio Analytics',
    'ai.close': 'Close AI',
    'ai.chat': 'Chat',
    'ai.memory': 'Memory',
    'ai.reports': 'Reports',
    'ai.placeholder': 'Ask about your portfolio...',
    'ai.recentQueries': 'Recent Queries',
    'ai.autoReports': 'Auto-Generated Reports',
    'ai.generated': 'Generated',
    'ai.view': 'View',
    'ai.welcome': 'Hello! I\'m your PMO AI Assistant. I can help you analyze your portfolio, identify risks, and generate custom reports. How can I help you today?',
  },
  ar: {
    // Navigation
    'nav.executive': 'نظرة المديرين التنفيذيين',
    'nav.portfolio': 'تحليل المحفظة المتعمق',
    'nav.project': 'عرض مدير المشروع',
    'nav.details': 'تفاصيل المشروع',
    'nav.components': 'مكتبة المكونات',
    
    // Executive Overview
    'exec.title': 'نظرة عامة على محفظة المشاريع التنفيذية',
    'exec.subtitle': 'هل نحن على المسار الصحيح للتسليم؟',
    'exec.portfolioHealth': 'صحة المحفظة',
    'exec.activeProjects': 'المشاريع النشطة',
    'exec.totalBudget': 'إجمالي الميزانية',
    'exec.avgConfidence': 'متوسط ثقة التسليم',
    'exec.onTrack': 'على المسار',
    'exec.atRisk': 'معرض للخطر',
    'exec.critical': 'حرج',
    'exec.strategicAlignment': 'التوافق الاستراتيجي',
    'exec.deliveryTrend': 'اتجاه ثقة التسليم',
    'exec.topRisks': 'أهم مخاطر المحفظة',
    'exec.budgetUtilization': 'استخدام الميزانية حسب المبادرة',
    'exec.upcomingMilestones': 'المعالم الحرجة القادمة',
    'exec.spi': 'متوسط SPI',
    'exec.cpi': 'متوسط CPI',
    'exec.projects': 'مشاريع',
    'exec.spent': 'المنفق',
    'exec.forecast': 'التوقعات',
    'exec.overBudget': 'فوق الميزانية',
    'exec.underBudget': 'تحت الميزانية',
    'exec.variance': 'الفرق',
    'exec.valueDelivery': 'تسليم القيمة',
    'exec.planned': 'المخطط',
    'exec.delivered': 'المُسلّم',
    'exec.deliveryRate': 'معدل التسليم',
    'exec.initiatives': 'المبادرات',
    'exec.overBudgetProjects': 'أعلى 5 مشاريع متجاوزة للميزانية',
    'exec.project': 'المشروع',
    'exec.pm': 'مدير المشروع',
    'exec.dueDate': 'تاريخ الاستحقاق',
    'exec.owner': 'المالك',
    'exec.probability': 'الاحتمالية',
    'exec.impact': 'التأثير',
    'exec.mitigation': 'التخفيف',
    'exec.activeFilters': 'الفلاتر النشطة',
    'exec.clearAll': 'مسح الكل',
    'exec.month': 'الشهر',
    'exec.confidence': 'الثقة',
    'exec.target': 'الهدف',
    
    // Portfolio Deep Dive
    'portfolio.title': 'تحليل المحفظة المتعمق',
    'portfolio.subtitle': 'ما هي المشاريع الفاشلة ولماذا؟',
    'portfolio.highRisk': 'مشاريع عالية المخاطر',
    'portfolio.openRisks': 'إجمالي المخاطر المفتوحة',
    'portfolio.overAllocated': 'الأدوار المخصصة بشكل زائد',
    'portfolio.milestoneAdherence': 'متوسط الالتزام بالمعالم',
    'portfolio.performanceMatrix': 'مصفوفة أداء المشروع (SPI مقابل CPI)',
    'portfolio.comparisonMatrix': 'مصفوفة مقارنة المشاريع المتعددة',
    'portfolio.riskConcentration': 'تركيز المخاطر (التأثير × الاحتمالية)',
    'portfolio.riskTypeDistribution': 'توزيع أنواع المخاطر',
    'portfolio.resourceUtilization': 'استخدام الموارد حسب الدور',
    'portfolio.milestoneTrend': 'اتجاه الالتزام بالمعالم',
    'portfolio.highRiskTable': 'مشاريع عالية المخاطر (6+ مخاطر مفتوحة)',
    'portfolio.openIssues': 'المشكلات المفتوحة',
    'portfolio.6plusRisks': '6+ مخاطر مفتوحة لكل منها',
    'portfolio.acrossAll': 'عبر جميع المشاريع',
    'portfolio.resourceConstraints': 'قيود الموارد',
    'portfolio.portfolioAvg': 'متوسط المحفظة',
    'portfolio.bubbleSize': 'حجم الفقاعة = الميزانية | اللون = الحالة | الأرباع: أعلى اليمين = أفضل أداء',
    'portfolio.investmentRisk': 'الاستثمار المعرض للخطر: الميزانية مقابل ثقة التسليم | حجم الفقاعة = المخاطر المفتوحة | أسفل اليمين = استثمار عالٍ، ثقة منخفضة',
    'portfolio.lowImpact': 'تأثير منخفض',
    'portfolio.mediumImpact': 'تأثير متوسط',
    'portfolio.highImpact': 'تأثير عالي',
    'portfolio.criticalImpact': 'تأثير حرج',
    'portfolio.highProb': 'عالية',
    'portfolio.mediumProb': 'متوسطة',
    'portfolio.lowProb': 'منخفضة',
    'portfolio.intensity': 'الكثافة:',
    'portfolio.low': 'منخفض',
    'portfolio.medium': 'متوسط',
    'portfolio.high': 'عالي',
    'portfolio.topRight': 'القيم الأعلى في أعلى اليمين = مخاطر أكثر حرجة',
    'portfolio.capacity': 'السعة',
    'portfolio.allocated': 'المخصص',
    'portfolio.overAllocation': 'تنبيهات التخصيص الزائد:',
    'portfolio.overCapacity': 'ساعة فوق السعة',
    'portfolio.plannedMilestones': 'المعالم المخططة',
    'portfolio.achievedMilestones': 'المعالم المحققة',
    'portfolio.forecastAccuracy': 'دقة التوقعات',
    'portfolio.improvingTrend': 'اتجاه متحسن',
    'portfolio.avgDelay': 'متوسط تأخير المعالم',
    'portfolio.days': 'أيام',
    'portfolio.downFrom': 'انخفاضاً من 6.5',
    'portfolio.highRiskZone': 'منطقة عالية المخاطر',
    'portfolio.highRiskDesc': 'الميزانية > 15 مليون دولار، الثقة < 70%',
    'portfolio.avgRiskExposure': 'متوسط التعرض للمخاطر',
    'portfolio.risksPerProject': 'مخاطر/مشروع',
    'portfolio.highConfidence': 'ثقة عالية',
    'portfolio.confidence80': 'الثقة ≥ 80%',
    'portfolio.schedulePerformance': 'مؤشر أداء الجدول الزمني (SPI)',
    'portfolio.costPerformance': 'مؤشر أداء التكلفة (CPI)',
    'portfolio.projectBudget': 'ميزانية المشروع (مليون دولار)',
    'portfolio.deliveryConfidence': 'ثقة التسليم (%)',
    'portfolio.confidenceThreshold': 'عتبة الثقة 70%',
    
    // Project Manager View
    'pm.title': 'عرض مدير المشروع',
    'pm.subtitle': 'ما الذي يعيقني هذا الأسبوع؟',
    'pm.weeklyFocus': 'التركيز الأسبوعي',
    'pm.schedulePerformance': 'أداء الجدول الزمني (EV مقابل PV)',
    'pm.costPerformance': 'أداء التكلفة',
    'pm.riskRegister': 'سجل المخاطر',
    'pm.issueLog': 'سجل المشكلات',
    'pm.resourceAllocation': 'تخصيص الموارد',
    'pm.tasksOverdue': 'المهام المتأخرة',
    'pm.blockers': 'المعوقات النشطة',
    'pm.teamVelocity': 'سرعة الفريق',
    'pm.sprintProgress': 'تقدم السباق',
    'pm.thisWeek': 'هذا الأسبوع',
    'pm.requiresAction': 'يتطلب إجراء',
    'pm.needsResolution': 'يحتاج إلى حل',
    'pm.pointsPerSprint': 'نقاط/سباق',
    'pm.stable': 'مستقر',
    'pm.completed': 'مكتمل',
    'pm.remaining': 'متبقي',
    'pm.earnedValue': 'القيمة المكتسبة (EV)',
    'pm.plannedValue': 'القيمة المخططة (PV)',
    'pm.actualCost': 'التكلفة الفعلية (AC)',
    'pm.description': 'الوصف',
    'pm.assignee': 'المعين',
    'pm.role': 'الدور',
    'pm.allocation': 'التخصيص',
    'pm.available': 'متاح',
    'pm.overAllocated': 'مخصص بشكل زائد',
    'pm.week': 'الأسبوع',
    
    // Project Details
    'details.title': 'التعمق في تفاصيل المشروع',
    'details.subtitle': 'أين تكمن الاختناقات؟',
    'details.overview': 'نظرة عامة على المشروع',
    'details.taskBreakdown': 'تفصيل المهام حسب المرحلة',
    'details.criticalPath': 'تحليل المسار الحرج',
    'details.burndown': 'مخطط الاحتراق السريع',
    'details.selectProject': 'اختر مشروعاً لعرض التفاصيل',
    'details.name': 'اسم المشروع',
    'details.manager': 'مدير المشروع',
    'details.phase': 'المرحلة الحالية',
    'details.progress': 'التقدم',
    'details.health': 'الصحة',
    'details.totalTasks': 'إجمالي المهام',
    'details.completedTasks': 'المكتملة',
    'details.inProgress': 'قيد التنفيذ',
    'details.blocked': 'محظورة',
    'details.longestTask': 'أطول مهمة على المسار الحرج',
    'details.criticalTasks': 'المهام الحرجة',
    'details.totalDuration': 'المدة الإجمالية',
    'details.atRiskTasks': 'المهام المعرضة للخطر',
    'details.ideal': 'مثالي',
    'details.actual': 'فعلي',
    'details.timeline': 'الجدول الزمني',
    'details.task': 'المهمة',
    'details.duration': 'المدة',
    'details.dependencies': 'التبعيات',
    'details.slack': 'المرونة',
    'details.design': 'التصميم',
    'details.development': 'التطوير',
    'details.testing': 'الاختبار',
    'details.deployment': 'النشر',
    'details.day': 'اليوم',
    'details.tasksRemaining': 'المهام المتبقية',
    
    // Common
    'common.status': 'الحالة',
    'common.budget': 'الميزانية',
    'common.confidence': 'الثقة',
    'common.risks': 'المخاطر',
    'common.issues': 'المشكلات',
    'common.view': 'عرض',
    'common.filters': 'الفلاتر',
    'common.all': 'الكل',
    'common.search': 'البحث عن المشاريع...',
    'common.portfolio': 'المحفظة',
    'common.program': 'البرنامج',
    'common.strategicInitiative': 'المبادرة الاستراتيجية',
    'common.projectManager': 'مدير المشروع',
    'common.spi': 'SPI',
    'common.cpi': 'CPI',
    'common.projects': 'مشاريع',
    
    // AI Assistant
    'ai.title': 'مساعد PMO الذكي',
    'ai.subtitle': 'مدعوم بتحليلات متقدمة للمحفظة',
    'ai.close': 'إغلاق المساعد',
    'ai.chat': 'محادثة',
    'ai.memory': 'الذاكرة',
    'ai.reports': 'تقارير',
    'ai.placeholder': 'اسأل عن المحفظة...',
    'ai.recentQueries': 'الاستفسارات الأخيرة',
    'ai.autoReports': 'التقارير المُنشأة تلقائياً',
    'ai.generated': 'تم الإنشاء',
    'ai.view': 'عرض',
    'ai.welcome': 'مرحباً! أنا مساعد PMO الذكي. يمكنني مساعدتك في تحليل محفظة المشاريع، تحديد المخاطر، وإنشاء تقارير مخصصة. كيف يمكنني مساعدتك اليوم؟',
  },
};