import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('pmo-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('pmo-language', language);
    if (language === 'ar') {
      document.documentElement.setAttribute('dir', 'rtl');
      document.documentElement.setAttribute('lang', 'ar');
    } else {
      document.documentElement.setAttribute('dir', 'ltr');
      document.documentElement.setAttribute('lang', 'en');
    }
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.executive': 'Executive Overview',
    'nav.portfolio': 'Portfolio Deep Dive',
    'nav.project': 'Project Manager',
    'nav.details': 'Project Details',
    'nav.components': 'Components Library',

    'exec.title': 'Executive Portfolio Overview',
    'exec.subtitle': 'Are we on track to deliver?',
    'exec.portfolioView': 'Portfolio View',
    'exec.milestoneView': 'Milestone View',

    'exec.portfolioHealthSection': 'Portfolio Health',
    'exec.financialPerformance': 'Financial Performance',
    'exec.milestoneDeliverySection': 'Milestone Delivery',

    'exec.portfolioHealthPct': 'Portfolio Health %',
    'exec.totalActiveProjects': 'Total Active Projects',
    'exec.onTrackProjectsPct': 'On Track Projects %',
    'exec.criticalProjects': 'Critical Projects',
    'exec.openRisksLabel': 'Open Risks',
    'exec.portfolioSPI': 'Portfolio SPI',
    'exec.portfolioCPI': 'Portfolio CPI',
    'exec.budgetVarianceLabel': 'Budget Variance',
    'exec.forecastAccuracyLabel': 'Forecast Accuracy',
    'exec.totalMilestonesLabel': 'Total Milestones',
    'exec.milestonesOnTrackLabel': 'Milestones On Track',
    'exec.milestonesAtRiskLabel': 'Milestones At Risk',
    'exec.milestonesDelayedLabel': 'Milestones Delayed',
    'exec.milestoneCompletionPct': 'Milestone Completion %',

    'exec.onTrackSub': 'on track',
    'exec.vsLastQuarterPlus3': '+3 vs last quarter',
    'exec.projectsCount': 'projects',
    'exec.immediateAction': 'immediate action',
    'exec.atRiskPlusCriticalSub': 'at risk',
    'exec.criticalSub': 'critical',
    'exec.schedulePerformanceSub': 'Schedule performance',
    'exec.costPerformanceSub': 'Cost performance',
    'exec.overBudgetSub': 'Over budget',
    'exec.underBudgetSub': 'Under budget',
    'exec.vsLastQuarterPlus2': '+2% vs last quarter',
    'exec.acrossAllProjects': 'across all projects',
    'exec.ofTotal': 'of total',
    'exec.needsAttention': 'needs attention',
    'exec.pastDueDate': 'past due date',
    'exec.completedSub': 'completed',

    'exec.portfolioPerformance': 'Portfolio Performance',
    'exec.pmoCycleHealth': 'PMO Cycle Health',
    'exec.departmentDistribution': 'Department Distribution',

    'exec.statusDistribution': 'Status Distribution',
    'exec.spiCpiTrend': 'SPI & CPI Trend (6 Months)',
    'exec.strategicAlignmentPct': 'Strategic Alignment %',
    'exec.overBudgetProjectsTitle': 'Top 5 Over-Budget Projects',
    'exec.delayedProjectsTitle': 'Top 5 Delayed Projects',
    'exec.pmoCycleStageDistribution': 'PMO Cycle Stage Distribution',
    'exec.milestoneStatusSummary': 'Milestone Status Summary',
    'exec.pmoStageBreakdown': 'PMO Stage Breakdown',
    'exec.departmentHealthStatus': 'Department Health Status',
    'exec.departmentBudgetUtil': 'Department Budget Utilization ($M)',
    'exec.departmentPortfolioSummary': 'Department Portfolio Summary',

    'exec.onTrack': 'On Track',
    'exec.atRisk': 'At Risk',
    'exec.critical': 'Critical',
    'exec.completed': 'Completed',
    'exec.delayed': 'Delayed',

    'exec.projectCol': 'Project',
    'exec.budgetCol': 'Budget',
    'exec.forecastCol': 'Forecast',
    'exec.varianceCol': 'Variance',
    'exec.statusCol': 'Status',
    'exec.spiCol': 'SPI',
    'exec.delayCol': 'Delay',
    'exec.pmCol': 'PM',
    'exec.stageCol': 'Stage',
    'exec.totalCol': 'Total',
    'exec.onTrackCol': 'On Track',
    'exec.atRiskCol': 'At Risk',
    'exec.criticalCol': 'Critical',
    'exec.completedCol': 'Completed',
    'exec.healthPctCol': 'Health %',
    'exec.departmentCol': 'Department',
    'exec.budgetMCol': 'Budget ($M)',
    'exec.spentMCol': 'Spent ($M)',
    'exec.alignmentPct': 'Alignment %',
    'exec.budgetLabel': 'Budget',
    'exec.spentLabel': 'Spent',

    'exec.activeFiltersLabel': 'Active Filters:',
    'exec.statusFilter': 'Status:',
    'exec.deptFilter': 'Dept:',
    'exec.clearAll': 'Clear All',

    'exec.portfolioHealth': 'Portfolio Health',
    'exec.activeProjects': 'Active Projects',
    'exec.totalBudget': 'Total Budget',
    'exec.avgConfidence': 'Avg. Delivery Confidence',
    'exec.strategicAlignment': 'Strategic Alignment',
    'exec.deliveryTrend': 'Delivery Confidence Trend',
    'exec.topRisks': 'Top Portfolio Risks',
    'exec.budgetUtilization': 'Budget Utilization by Initiative',
    'exec.upcomingMilestones': 'Upcoming Critical Milestones',
    'exec.spi': 'Avg. SPI',
    'exec.cpi': 'Avg. CPI',
    'exec.projects': 'projects',
    'exec.spent': 'Spent',
    'exec.forecast': 'Forecast',
    'exec.overBudget': 'Over Budget',
    'exec.underBudget': 'Under Budget',
    'exec.variance': 'Variance',
    'exec.valueDelivery': 'Value Delivery',
    'exec.planned': 'Planned',
    'exec.delivered': 'Delivered',
    'exec.deliveryRate': 'Delivery Rate',
    'exec.initiatives': 'Initiatives',
    'exec.overBudgetProjects': 'Top 5 Over-Budget Projects',
    'exec.project': 'Project',
    'exec.pm': 'PM',
    'exec.dueDate': 'Due Date',
    'exec.owner': 'Owner',
    'exec.probability': 'Probability',
    'exec.impact': 'Impact',
    'exec.mitigation': 'Mitigation',
    'exec.activeFilters': 'Active Filters',
    'exec.month': 'Month',
    'exec.confidence': 'Confidence',
    'exec.target': 'Target',

    'tooltip.howCalculated': "How it's calculated:",
    'tooltip.portfolioHealth': 'Percentage of projects with "On Track" status. Formula: (On Track Projects / Total Projects) × 100',
    'tooltip.totalProjects': 'Count of all projects in the portfolio with active status (not completed or cancelled).',
    'tooltip.onTrackPct': 'Projects meeting both schedule (SPI ≥ 0.95) and cost (CPI ≥ 0.95) targets with no critical issues.',
    'tooltip.critical': 'Projects with SPI < 0.8 or CPI < 0.8, or those with 6+ open high-impact risks requiring immediate executive intervention.',
    'tooltip.openRisks': 'Count of projects with "At Risk" or "Critical" status that have unresolved issues affecting timeline or budget.',
    'tooltip.spi': 'Schedule Performance Index = Earned Value / Planned Value. > 1.0 = ahead of schedule, < 1.0 = behind schedule. Averaged across all projects.',
    'tooltip.cpi': 'Cost Performance Index = Earned Value / Actual Cost. > 1.0 = under budget, < 1.0 = over budget. Averaged across all projects.',
    'tooltip.budgetVariance': 'Total Forecast Cost - Total Budget. Positive = over budget, Negative = under budget. Sum across all active projects.',
    'tooltip.forecastAccuracy': 'Percentage of projects where final cost was within ±10% of forecasted cost. Higher = better prediction accuracy.',
    'tooltip.totalMilestones': 'Count of all planned milestones across active projects, including completed, in-progress, and upcoming milestones.',
    'tooltip.milestonesOnTrack': 'Milestones expected to be completed by their planned date based on current progress and no blocking issues.',
    'tooltip.milestonesAtRisk': 'Milestones with potential delays due to dependencies, resource constraints, or project slippage.',
    'tooltip.milestonesDelayed': 'Milestones that have passed their planned completion date without being marked complete.',
    'tooltip.milestoneCompletion': 'Formula: (Completed Milestones / Total Milestones) × 100. Shows overall portfolio progress.',

    'chart.statusDistDesc': 'Shows the breakdown of all projects by their current status (On Track, At Risk, Critical, Completed). Helps identify the overall health of the portfolio at a glance.',
    'chart.spiCpiTrendDesc': 'Tracks Schedule Performance Index (SPI) and Cost Performance Index (CPI) over the last 6 months. Values above 1.0 indicate ahead of schedule/under budget; below 1.0 means behind schedule/over budget.',
    'chart.strategicAlignDesc': 'Measures how well the portfolio aligns with each strategic initiative. Higher percentages indicate stronger alignment between projects and organizational goals.',
    'chart.overBudgetDesc': 'Lists the top 5 projects with the largest budget overruns, showing budget vs forecast variance. These projects need immediate financial review.',
    'chart.delayedDesc': 'Lists the top 5 projects with the most schedule delays based on SPI. Lower SPI indicates greater schedule slippage requiring corrective action.',
    'chart.pmoCycleStageDesc': 'Shows milestone distribution across PMO lifecycle stages (Initiation through Closure). Each bar is stacked by status: Completed, On Track, and At Risk.',
    'chart.milestoneStatusDesc': 'Quick overview of milestone counts by status: Completed, On Track, At Risk, and Delayed. Provides an at-a-glance view of delivery health.',
    'chart.pmoStageBreakdownDesc': 'Detailed table showing milestone health per PMO stage, including completed, on track, and at risk counts with health percentage.',
    'chart.deptHealthDesc': 'Stacked bar chart showing project status distribution per department. Identifies which departments have the most critical or at-risk projects.',
    'chart.deptBudgetDesc': 'Compares allocated budget vs actual spend for each department. Helps identify departments that are overspending or underspending their budgets.',
    'chart.deptSummaryDesc': 'Comprehensive table with project counts, status breakdown, budget allocation, spend, and health percentage for each department.',

    'ms.milestoneStatusOverview': 'Milestone Status Overview',
    'ms.criticalPathHealth': 'Critical Path Health',
    'ms.deliveryPerformance': 'Delivery Performance',
    'ms.totalMilestones': 'Total Milestones',
    'ms.completed': 'Completed',
    'ms.onTrack': 'On Track',
    'ms.atRisk': 'At Risk',
    'ms.delayed': 'Delayed',
    'ms.upcoming': 'Upcoming',
    'ms.criticalPathSub': 'critical path',
    'ms.ofTotal': 'of total',
    'ms.requiresAction': 'requires action',
    'ms.next30Days': 'next 30 days',
    'ms.totalCriticalPath': 'Total Critical Path',
    'ms.criticalPathOnTrack': 'Critical Path On Track',
    'ms.criticalPathAtRisk': 'Critical Path At Risk',
    'ms.healthy': 'healthy',
    'ms.immediateAction': 'immediate action',
    'ms.completionRate': 'Completion Rate',
    'ms.vsLastMonth': '+3% vs last month',
    'ms.plannedYTD': 'Planned YTD',
    'ms.totalPlanned': 'total planned',
    'ms.actualYTD': 'Actual YTD',
    'ms.ofPlanned': '91% of planned',
    'ms.onTimeDelivery': 'On-Time Delivery %',
    'ms.improvement': '+5% improvement',
    'ms.averageDelay': 'Average Delay (Days)',
    'ms.forDelayedItems': 'for delayed items',

    'ms.milestonePerformance': 'Milestone Performance',
    'ms.stageAnalysis': 'Stage Analysis',
    'ms.riskDelays': 'Risk & Delays',

    'ms.ragDistribution': 'Milestone RAG Distribution',
    'ms.criticalPathStatus': 'Critical Path Status',
    'ms.completionTrend': 'Completion Trend (6 Months)',
    'ms.completionMetrics': 'Completion Metrics',
    'ms.statusBreakdown': 'Status Breakdown',
    'ms.pmoCycleStageDistribution': 'PMO Cycle Stage Distribution',
    'ms.pmoStageDefinitions': 'PMO Stage Definitions',
    'ms.pmoStageBreakdown': 'PMO Stage Breakdown',
    'ms.atRiskByDepartment': 'At Risk by Department',
    'ms.riskSummary': 'Risk Summary',
    'ms.top10Delayed': 'Top 10 Delayed Milestones',
    'ms.atRiskByDeptTable': 'Milestones At Risk by Department',

    'ms.initiation': 'Initiation',
    'ms.initiationDesc': 'Requirements gathering & project approval',
    'ms.planning': 'Planning',
    'ms.planningDesc': 'Design phase & resource allocation',
    'ms.execution': 'Execution',
    'ms.executionDesc': 'Development & delivery phase',
    'ms.monitoring': 'Monitoring',
    'ms.monitoringDesc': 'Testing & validation phase',
    'ms.closure': 'Closure',
    'ms.closureDesc': 'Go-live & handover to operations',

    'ms.milestoneCol': 'Milestone',
    'ms.projectCol': 'Project',
    'ms.stageCol': 'Stage',
    'ms.criticalCol': 'Critical',
    'ms.ownerCol': 'Owner',
    'ms.departmentCol': 'Department',
    'ms.atRiskCol': 'At Risk',
    'ms.criticalPathCol': 'Critical Path',
    'ms.pctOfTotalCol': '% of Total',
    'ms.totalCol': 'Total',
    'ms.completedCol': 'Completed',
    'ms.onTrackCol': 'On Track',
    'ms.healthPctCol': 'Health %',

    'ms.critPathMilestonesAtRisk': 'Critical Path Milestones At Risk',
    'ms.delayedMilestonesLabel': 'Delayed Milestones',
    'ms.actionRequired': 'Action Required:',
    'ms.actionRequiredText1': 'Immediate attention needed for',
    'ms.actionRequiredText2': 'critical path milestones to avoid project delays.',
    'ms.planned': 'Planned',
    'ms.actual': 'Actual',
    'ms.totalCriticalPathLabel': 'Total Critical Path',

    'ms.tooltip.totalMilestones': 'Count of all milestones across active projects, including completed, on-track, at-risk, delayed, and upcoming statuses.',
    'ms.tooltip.completed': 'Milestones marked as completed with all deliverables signed off and verified.',
    'ms.tooltip.onTrack': 'Milestones progressing as planned with no impediments, expected to complete by target date.',
    'ms.tooltip.atRisk': 'Milestones facing potential delays due to dependencies, resource issues, or scope changes that may impact timeline.',
    'ms.tooltip.delayed': 'Milestones that have passed their planned date without completion, requiring immediate corrective action.',
    'ms.tooltip.upcoming': 'Milestones scheduled within the next 30 days that haven\'t started yet or are in early planning stages.',
    'ms.tooltip.totalCriticalPath': 'Milestones on the critical path where any delay directly impacts project completion date.',
    'ms.tooltip.criticalPathOnTrack': 'Critical path milestones progressing on schedule with no issues. Essential for on-time project delivery.',
    'ms.tooltip.criticalPathAtRisk': 'Critical path milestones that are delayed or at-risk. Immediate executive attention required to avoid project delays.',
    'ms.tooltip.completionRate': 'Formula: (Completed Milestones / Total Milestones) × 100. Measures portfolio-wide delivery progress.',
    'ms.tooltip.plannedYTD': 'Total number of milestones planned to be completed from January 1 to current date this year.',
    'ms.tooltip.actualYTD': 'Number of milestones actually completed from January 1 to current date this year.',
    'ms.tooltip.onTimeDelivery': 'Percentage of completed milestones delivered by or before their planned date. Higher = better delivery discipline.',
    'ms.tooltip.avgDelay': 'Average number of days past target date for delayed milestones. Lower = better recovery capability.',

    'ms.chart.ragDistDesc': 'Pie chart showing milestones by RAG status (Red/Amber/Green). Identifies the proportion of milestones that are delayed, at risk, on track, or completed.',
    'ms.chart.critPathDesc': 'Shows the health of critical path milestones. Critical path items directly impact the project end date — at-risk items here need immediate escalation.',
    'ms.chart.completionTrendDesc': 'Tracks planned vs actual milestone completions over 6 months. A widening gap between lines indicates growing delivery delays.',
    'ms.chart.completionMetricsDesc': 'Key delivery metrics: planned vs actual milestones completed year-to-date, and the overall completion rate with month-over-month trend.',
    'ms.chart.statusBreakdownDesc': 'Count of milestones in each status category. Use this to quickly assess how many milestones need attention across the portfolio.',
    'ms.chart.stageDistDesc': 'Stacked bar chart showing milestone status distribution across each PMO lifecycle stage. Helps identify which stages have the most delivery risk.',
    'ms.chart.stageBreakdownDesc': 'Detailed table showing milestone counts by status for each PMO stage, with health percentage calculated from on-track milestones.',
    'ms.chart.atRiskByDeptDesc': 'Bar chart comparing at-risk and critical path milestone counts by department. Identifies which departments carry the highest delivery risk.',
    'ms.chart.riskSummaryDesc': 'High-level risk dashboard showing critical path milestones at risk and total delayed milestones requiring immediate management attention.',
    'ms.chart.top10DelayedDesc': 'Lists the most critical delayed milestones with their project, stage, critical path status, and owner. Prioritize action on critical path items first.',
    'ms.chart.atRiskByDeptTableDesc': 'Department-level breakdown showing at-risk counts, critical path items, and percentage of total at-risk milestones per department.',

    'month.oct': 'Oct',
    'month.nov': 'Nov',
    'month.dec': 'Dec',
    'month.jan': 'Jan',
    'month.feb': 'Feb',
    'month.mar': 'Mar',

    'portfolio.title': 'Portfolio Deep Dive',
    'portfolio.subtitle': 'Which projects are failing and why?',
    'portfolio.highRisk': 'High-Risk Projects',
    'portfolio.openRisks': 'Total Open Risks',
    'portfolio.overAllocated': 'Over-Allocated Roles',
    'portfolio.milestoneAdherence': 'Avg Milestone Adherence',
    'portfolio.performanceMatrix': 'Project Performance Matrix (SPI vs CPI)',
    'portfolio.comparisonMatrix': 'Multi-Project Comparison Matrix',
    'portfolio.riskConcentration': 'Risk Concentration (Impact × Probability)',
    'portfolio.riskTypeDistribution': 'Risk Type Distribution',
    'portfolio.resourceUtilization': 'Resource Utilization by Role',
    'portfolio.milestoneTrend': 'Milestone Adherence Trend',
    'portfolio.highRiskTable': 'High-Risk Projects (6+ Open Risks)',
    'portfolio.openIssues': 'Open Issues',
    'portfolio.6plusRisks': '6+ open risks each',
    'portfolio.acrossAll': 'Across all projects',
    'portfolio.resourceConstraints': 'Resource constraints',
    'portfolio.portfolioAvg': 'Portfolio average',
    'portfolio.bubbleSize': 'Bubble size = Budget | Color = Status | Quadrants: Top-right = Best Performance',
    'portfolio.investmentRisk': 'Investment at Risk: Budget vs Delivery Confidence | Bubble size = Open Risks | Bottom-right = High investment, low confidence',
    'portfolio.lowImpact': 'Low Impact',
    'portfolio.mediumImpact': 'Medium Impact',
    'portfolio.highImpact': 'High Impact',
    'portfolio.criticalImpact': 'Critical Impact',
    'portfolio.highProb': 'High',
    'portfolio.mediumProb': 'Medium',
    'portfolio.lowProb': 'Low',
    'portfolio.intensity': 'Intensity:',
    'portfolio.low': 'Low',
    'portfolio.medium': 'Medium',
    'portfolio.high': 'High',
    'portfolio.topRight': 'Higher values in top-right = More critical risks',
    'portfolio.capacity': 'Capacity',
    'portfolio.allocated': 'Allocated',
    'portfolio.overAllocation': 'Over-Allocation Alerts:',
    'portfolio.overCapacity': 'h over capacity',
    'portfolio.plannedMilestones': 'Planned Milestones',
    'portfolio.achievedMilestones': 'Achieved Milestones',
    'portfolio.forecastAccuracy': 'Forecast Accuracy',
    'portfolio.improvingTrend': 'Improving trend',
    'portfolio.avgDelay': 'Avg Milestone Delay',
    'portfolio.days': 'days',
    'portfolio.downFrom': 'Down from 6.5',
    'portfolio.highRiskZone': 'High Risk Zone',
    'portfolio.highRiskDesc': 'Budget > $15M, Confidence < 70%',
    'portfolio.avgRiskExposure': 'Avg Risk Exposure',
    'portfolio.risksPerProject': 'risks/project',
    'portfolio.highConfidence': 'High Confidence',
    'portfolio.confidence80': 'Confidence ≥ 80%',
    'portfolio.schedulePerformance': 'Schedule Performance Index (SPI)',
    'portfolio.costPerformance': 'Cost Performance Index (CPI)',
    'portfolio.projectBudget': 'Project Budget ($M)',
    'portfolio.deliveryConfidence': 'Delivery Confidence (%)',
    'portfolio.confidenceThreshold': '70% Confidence Threshold',

    'pm.title': 'Project Manager View',
    'pm.subtitle': "What's blocking me this week?",
    'pm.weeklyFocus': 'Weekly Focus',
    'pm.schedulePerformance': 'Schedule Performance (EV vs PV)',
    'pm.costPerformance': 'Cost Performance',
    'pm.riskRegister': 'Risk Register',
    'pm.issueLog': 'Issue Log',
    'pm.resourceAllocation': 'Resource Allocation',
    'pm.tasksOverdue': 'Tasks Overdue',
    'pm.blockers': 'Active Blockers',
    'pm.teamVelocity': 'Team Velocity',
    'pm.sprintProgress': 'Sprint Progress',
    'pm.thisWeek': 'This Week',
    'pm.requiresAction': 'Requires action',
    'pm.needsResolution': 'Needs resolution',
    'pm.pointsPerSprint': 'points/sprint',
    'pm.stable': 'Stable',
    'pm.completed': 'Completed',
    'pm.remaining': 'Remaining',
    'pm.earnedValue': 'Earned Value (EV)',
    'pm.plannedValue': 'Planned Value (PV)',
    'pm.actualCost': 'Actual Cost (AC)',
    'pm.description': 'Description',
    'pm.assignee': 'Assignee',
    'pm.role': 'Role',
    'pm.allocation': 'Allocation',
    'pm.available': 'Available',
    'pm.overAllocated': 'Over-allocated',
    'pm.week': 'Week',

    'details.title': 'Project Detail Drill-Down',
    'details.subtitle': 'Where are the bottlenecks?',
    'details.overview': 'Project Overview',
    'details.taskBreakdown': 'Task Breakdown by Phase',
    'details.criticalPath': 'Critical Path Analysis',
    'details.burndown': 'Sprint Burndown',
    'details.selectProject': 'Select a project to view details',
    'details.name': 'Project Name',
    'details.manager': 'Project Manager',
    'details.phase': 'Current Phase',
    'details.progress': 'Progress',
    'details.health': 'Health',
    'details.totalTasks': 'Total Tasks',
    'details.completedTasks': 'Completed',
    'details.inProgress': 'In Progress',
    'details.blocked': 'Blocked',
    'details.longestTask': 'Longest Task on Critical Path',
    'details.criticalTasks': 'Critical Tasks',
    'details.totalDuration': 'Total Duration',
    'details.atRiskTasks': 'At-Risk Tasks',
    'details.ideal': 'Ideal',
    'details.actual': 'Actual',
    'details.timeline': 'Timeline',
    'details.task': 'Task',
    'details.duration': 'Duration',
    'details.dependencies': 'Dependencies',
    'details.slack': 'Slack',
    'details.design': 'Design',
    'details.development': 'Development',
    'details.testing': 'Testing',
    'details.deployment': 'Deployment',
    'details.day': 'Day',
    'details.tasksRemaining': 'Tasks Remaining',

    'statusBadge.open': 'Open',
    'statusBadge.mitigated': 'Mitigated',
    'statusBadge.closed': 'Closed',
    'common.daysShort': 'd',
    'common.unknown': 'Unknown',
    'common.national': 'National',
    'common.council': 'Council',
    'common.status': 'Status',
    'common.budget': 'Budget',
    'common.confidence': 'Confidence',
    'common.risks': 'Risks',
    'common.issues': 'Issues',
    'common.view': 'View',
    'common.filters': 'Filters',
    'common.all': 'All',
    'common.search': 'Search projects...',
    'common.portfolio': 'Portfolio',
    'common.program': 'Program',
    'common.strategicInitiative': 'Strategic Initiative',
    'common.projectManager': 'Project Manager',
    'common.spi': 'SPI',
    'common.cpi': 'CPI',
    'common.projects': 'projects',

    'ai.title': 'PMO AI Assistant',
    'ai.subtitle': 'Powered by Advanced Portfolio Analytics',
    'ai.close': 'Close AI',
    'ai.chat': 'Chat',
    'ai.memory': 'Memory',
    'ai.reports': 'Reports',
    'ai.placeholder': 'Ask about your portfolio...',
    'ai.recentQueries': 'Recent Queries',
    'ai.autoReports': 'Auto-Generated Reports',
    'ai.generated': 'Generated',
    'ai.view': 'View',
    'ai.welcome': 'Hello! I\'m your PMO AI Assistant. I can help you analyze your portfolio, identify risks, and generate custom reports. How can I help you today?',
  },
  ar: {
    'nav.executive': 'نظرة المديرين التنفيذيين',
    'nav.portfolio': 'تحليل المحفظة المتعمق',
    'nav.project': 'عرض مدير المشروع',
    'nav.details': 'تفاصيل المشروع',
    'nav.components': 'مكتبة المكونات',

    'exec.title': 'نظرة عامة على محفظة المشاريع التنفيذية',
    'exec.subtitle': 'هل نحن على المسار الصحيح للتسليم؟',
    'exec.portfolioView': 'عرض المحفظة',
    'exec.milestoneView': 'عرض المعالم',

    'exec.portfolioHealthSection': 'صحة المحفظة',
    'exec.financialPerformance': 'الأداء المالي',
    'exec.milestoneDeliverySection': 'تسليم المعالم',

    'exec.portfolioHealthPct': 'صحة المحفظة %',
    'exec.totalActiveProjects': 'إجمالي المشاريع النشطة',
    'exec.onTrackProjectsPct': 'نسبة المشاريع على المسار %',
    'exec.criticalProjects': 'المشاريع الحرجة',
    'exec.openRisksLabel': 'المخاطر المفتوحة',
    'exec.portfolioSPI': 'مؤشر أداء الجدول',
    'exec.portfolioCPI': 'مؤشر أداء التكلفة',
    'exec.budgetVarianceLabel': 'فرق الميزانية',
    'exec.forecastAccuracyLabel': 'دقة التوقعات',
    'exec.totalMilestonesLabel': 'إجمالي المعالم',
    'exec.milestonesOnTrackLabel': 'معالم على المسار',
    'exec.milestonesAtRiskLabel': 'معالم معرضة للخطر',
    'exec.milestonesDelayedLabel': 'معالم متأخرة',
    'exec.milestoneCompletionPct': 'نسبة إنجاز المعالم %',

    'exec.onTrackSub': 'على المسار',
    'exec.vsLastQuarterPlus3': '+3 مقارنة بالربع السابق',
    'exec.projectsCount': 'مشاريع',
    'exec.immediateAction': 'إجراء فوري',
    'exec.atRiskPlusCriticalSub': 'معرض للخطر',
    'exec.criticalSub': 'حرج',
    'exec.schedulePerformanceSub': 'أداء الجدول الزمني',
    'exec.costPerformanceSub': 'أداء التكلفة',
    'exec.overBudgetSub': 'فوق الميزانية',
    'exec.underBudgetSub': 'تحت الميزانية',
    'exec.vsLastQuarterPlus2': '+2% مقارنة بالربع السابق',
    'exec.acrossAllProjects': 'عبر جميع المشاريع',
    'exec.ofTotal': 'من الإجمالي',
    'exec.needsAttention': 'يحتاج اهتمام',
    'exec.pastDueDate': 'تجاوز الموعد',
    'exec.completedSub': 'مكتمل',

    'exec.portfolioPerformance': 'أداء المحفظة',
    'exec.pmoCycleHealth': 'صحة دورة PMO',
    'exec.departmentDistribution': 'توزيع الأقسام',

    'exec.statusDistribution': 'توزيع الحالات',
    'exec.spiCpiTrend': 'اتجاه SPI و CPI (6 أشهر)',
    'exec.strategicAlignmentPct': 'نسبة التوافق الاستراتيجي %',
    'exec.overBudgetProjectsTitle': 'أعلى 5 مشاريع متجاوزة للميزانية',
    'exec.delayedProjectsTitle': 'أعلى 5 مشاريع متأخرة',
    'exec.pmoCycleStageDistribution': 'توزيع مراحل دورة PMO',
    'exec.milestoneStatusSummary': 'ملخص حالة المعالم',
    'exec.pmoStageBreakdown': 'تفصيل مراحل PMO',
    'exec.departmentHealthStatus': 'حالة صحة الأقسام',
    'exec.departmentBudgetUtil': 'استخدام ميزانية الأقسام (مليون $)',
    'exec.departmentPortfolioSummary': 'ملخص محفظة الأقسام',

    'exec.onTrack': 'على المسار',
    'exec.atRisk': 'معرض للخطر',
    'exec.critical': 'حرج',
    'exec.completed': 'مكتمل',
    'exec.delayed': 'متأخر',

    'exec.projectCol': 'المشروع',
    'exec.budgetCol': 'الميزانية',
    'exec.forecastCol': 'التوقعات',
    'exec.varianceCol': 'الفرق',
    'exec.statusCol': 'الحالة',
    'exec.spiCol': 'SPI',
    'exec.delayCol': 'التأخير',
    'exec.pmCol': 'م.م',
    'exec.stageCol': 'المرحلة',
    'exec.totalCol': 'الإجمالي',
    'exec.onTrackCol': 'على المسار',
    'exec.atRiskCol': 'معرض للخطر',
    'exec.criticalCol': 'حرج',
    'exec.completedCol': 'مكتمل',
    'exec.healthPctCol': 'الصحة %',
    'exec.departmentCol': 'القسم',
    'exec.budgetMCol': 'الميزانية (مليون $)',
    'exec.spentMCol': 'المنفق (مليون $)',
    'exec.alignmentPct': 'التوافق %',
    'exec.budgetLabel': 'الميزانية',
    'exec.spentLabel': 'المنفق',

    'exec.activeFiltersLabel': 'الفلاتر النشطة:',
    'exec.statusFilter': 'الحالة:',
    'exec.deptFilter': 'القسم:',
    'exec.clearAll': 'مسح الكل',

    'exec.portfolioHealth': 'صحة المحفظة',
    'exec.activeProjects': 'المشاريع النشطة',
    'exec.totalBudget': 'إجمالي الميزانية',
    'exec.avgConfidence': 'متوسط ثقة التسليم',
    'exec.strategicAlignment': 'التوافق الاستراتيجي',
    'exec.deliveryTrend': 'اتجاه ثقة التسليم',
    'exec.topRisks': 'أهم مخاطر المحفظة',
    'exec.budgetUtilization': 'استخدام الميزانية حسب المبادرة',
    'exec.upcomingMilestones': 'المعالم الحرجة القادمة',
    'exec.spi': 'متوسط SPI',
    'exec.cpi': 'متوسط CPI',
    'exec.projects': 'مشاريع',
    'exec.spent': 'المنفق',
    'exec.forecast': 'التوقعات',
    'exec.overBudget': 'فوق الميزانية',
    'exec.underBudget': 'تحت الميزانية',
    'exec.variance': 'الفرق',
    'exec.valueDelivery': 'تسليم القيمة',
    'exec.planned': 'المخطط',
    'exec.delivered': 'المُسلّم',
    'exec.deliveryRate': 'معدل التسليم',
    'exec.initiatives': 'المبادرات',
    'exec.overBudgetProjects': 'أعلى 5 مشاريع متجاوزة للميزانية',
    'exec.project': 'المشروع',
    'exec.pm': 'مدير المشروع',
    'exec.dueDate': 'تاريخ الاستحقاق',
    'exec.owner': 'المالك',
    'exec.probability': 'الاحتمالية',
    'exec.impact': 'التأثير',
    'exec.mitigation': 'التخفيف',
    'exec.activeFilters': 'الفلاتر النشطة',
    'exec.month': 'الشهر',
    'exec.confidence': 'الثقة',
    'exec.target': 'الهدف',

    'tooltip.howCalculated': 'كيف يتم حسابه:',
    'tooltip.portfolioHealth': 'نسبة المشاريع ذات الحالة "على المسار". الصيغة: (المشاريع على المسار / إجمالي المشاريع) × 100',
    'tooltip.totalProjects': 'عدد جميع المشاريع في المحفظة ذات الحالة النشطة (غير مكتملة أو ملغاة).',
    'tooltip.onTrackPct': 'المشاريع التي تحقق أهداف الجدول الزمني (SPI ≥ 0.95) والتكلفة (CPI ≥ 0.95) بدون مشكلات حرجة.',
    'tooltip.critical': 'المشاريع ذات SPI < 0.8 أو CPI < 0.8، أو تلك التي لديها 6+ مخاطر عالية التأثير تتطلب تدخلاً تنفيذياً فورياً.',
    'tooltip.openRisks': 'عدد المشاريع ذات الحالة "معرض للخطر" أو "حرج" التي لديها مشكلات لم تُحل تؤثر على الجدول الزمني أو الميزانية.',
    'tooltip.spi': 'مؤشر أداء الجدول الزمني = القيمة المكتسبة / القيمة المخططة. > 1.0 = متقدم على الجدول، < 1.0 = متأخر عن الجدول. متوسط عبر جميع المشاريع.',
    'tooltip.cpi': 'مؤشر أداء التكلفة = القيمة المكتسبة / التكلفة الفعلية. > 1.0 = تحت الميزانية، < 1.0 = فوق الميزانية. متوسط عبر جميع المشاريع.',
    'tooltip.budgetVariance': 'إجمالي التكلفة المتوقعة - إجمالي الميزانية. موجب = فوق الميزانية، سالب = تحت الميزانية. المجموع عبر جميع المشاريع النشطة.',
    'tooltip.forecastAccuracy': 'نسبة المشاريع التي كانت تكلفتها النهائية ضمن ±10% من التكلفة المتوقعة. أعلى = دقة توقع أفضل.',
    'tooltip.totalMilestones': 'عدد جميع المعالم المخططة عبر المشاريع النشطة، بما في ذلك المكتملة والجارية والقادمة.',
    'tooltip.milestonesOnTrack': 'المعالم المتوقع إكمالها بحلول تاريخها المخطط بناءً على التقدم الحالي وعدم وجود مشكلات معيقة.',
    'tooltip.milestonesAtRisk': 'المعالم التي تواجه تأخيرات محتملة بسبب التبعيات أو قيود الموارد أو انزلاق المشروع.',
    'tooltip.milestonesDelayed': 'المعالم التي تجاوزت تاريخ إكمالها المخطط دون اكتمالها.',
    'tooltip.milestoneCompletion': 'الصيغة: (المعالم المكتملة / إجمالي المعالم) × 100. يوضح التقدم الإجمالي للمحفظة.',

    'chart.statusDistDesc': 'يعرض توزيع جميع المشاريع حسب حالتها الحالية (على المسار، معرض للخطر، حرج، مكتمل). يساعد في تحديد الصحة العامة للمحفظة بنظرة واحدة.',
    'chart.spiCpiTrendDesc': 'يتتبع مؤشر أداء الجدول الزمني (SPI) ومؤشر أداء التكلفة (CPI) خلال الأشهر الستة الأخيرة. القيم فوق 1.0 تعني متقدم/تحت الميزانية؛ تحت 1.0 تعني متأخر/فوق الميزانية.',
    'chart.strategicAlignDesc': 'يقيس مدى توافق المحفظة مع كل مبادرة استراتيجية. النسب الأعلى تشير إلى توافق أقوى بين المشاريع والأهداف المؤسسية.',
    'chart.overBudgetDesc': 'يعرض أعلى 5 مشاريع بأكبر تجاوزات للميزانية، موضحاً الفرق بين الميزانية والتوقعات. تحتاج هذه المشاريع لمراجعة مالية فورية.',
    'chart.delayedDesc': 'يعرض أعلى 5 مشاريع بأكبر تأخيرات في الجدول بناءً على SPI. انخفاض SPI يشير إلى انزلاق أكبر في الجدول يتطلب إجراءات تصحيحية.',
    'chart.pmoCycleStageDesc': 'يعرض توزيع المعالم عبر مراحل دورة حياة PMO (من البدء إلى الإغلاق). كل شريط مكدس حسب الحالة: مكتمل، على المسار، ومعرض للخطر.',
    'chart.milestoneStatusDesc': 'نظرة سريعة على أعداد المعالم حسب الحالة: مكتمل، على المسار، معرض للخطر، ومتأخر. يوفر عرضاً فورياً لصحة التسليم.',
    'chart.pmoStageBreakdownDesc': 'جدول تفصيلي يعرض صحة المعالم لكل مرحلة PMO، بما في ذلك أعداد المكتملة والتي على المسار والمعرضة للخطر مع نسبة الصحة.',
    'chart.deptHealthDesc': 'رسم بياني شريطي مكدس يعرض توزيع حالة المشاريع لكل قسم. يحدد الأقسام التي لديها أكثر المشاريع الحرجة أو المعرضة للخطر.',
    'chart.deptBudgetDesc': 'يقارن الميزانية المخصصة مع الإنفاق الفعلي لكل قسم. يساعد في تحديد الأقسام التي تتجاوز أو تقلل إنفاق ميزانياتها.',
    'chart.deptSummaryDesc': 'جدول شامل يتضمن أعداد المشاريع، توزيع الحالات، تخصيص الميزانية، الإنفاق، ونسبة الصحة لكل قسم.',

    'ms.milestoneStatusOverview': 'نظرة عامة على حالة المعالم',
    'ms.criticalPathHealth': 'صحة المسار الحرج',
    'ms.deliveryPerformance': 'أداء التسليم',
    'ms.totalMilestones': 'إجمالي المعالم',
    'ms.completed': 'مكتمل',
    'ms.onTrack': 'على المسار',
    'ms.atRisk': 'معرض للخطر',
    'ms.delayed': 'متأخر',
    'ms.upcoming': 'قادم',
    'ms.criticalPathSub': 'مسار حرج',
    'ms.ofTotal': 'من الإجمالي',
    'ms.requiresAction': 'يتطلب إجراء',
    'ms.next30Days': 'خلال 30 يوم',
    'ms.totalCriticalPath': 'إجمالي المسار الحرج',
    'ms.criticalPathOnTrack': 'المسار الحرج على المسار',
    'ms.criticalPathAtRisk': 'المسار الحرج معرض للخطر',
    'ms.healthy': 'سليم',
    'ms.immediateAction': 'إجراء فوري',
    'ms.completionRate': 'معدل الإنجاز',
    'ms.vsLastMonth': '+3% مقارنة بالشهر السابق',
    'ms.plannedYTD': 'المخطط حتى الآن',
    'ms.totalPlanned': 'إجمالي المخطط',
    'ms.actualYTD': 'الفعلي حتى الآن',
    'ms.ofPlanned': '91% من المخطط',
    'ms.onTimeDelivery': 'نسبة التسليم في الوقت %',
    'ms.improvement': '+5% تحسن',
    'ms.averageDelay': 'متوسط التأخير (أيام)',
    'ms.forDelayedItems': 'للعناصر المتأخرة',

    'ms.milestonePerformance': 'أداء المعالم',
    'ms.stageAnalysis': 'تحليل المراحل',
    'ms.riskDelays': 'المخاطر والتأخيرات',

    'ms.ragDistribution': 'توزيع RAG للمعالم',
    'ms.criticalPathStatus': 'حالة المسار الحرج',
    'ms.completionTrend': 'اتجاه الإنجاز (6 أشهر)',
    'ms.completionMetrics': 'مقاييس الإنجاز',
    'ms.statusBreakdown': 'تفصيل الحالات',
    'ms.pmoCycleStageDistribution': 'توزيع مراحل دورة PMO',
    'ms.pmoStageDefinitions': 'تعريفات مراحل PMO',
    'ms.pmoStageBreakdown': 'تفصيل مراحل PMO',
    'ms.atRiskByDepartment': 'المعرضة للخطر حسب القسم',
    'ms.riskSummary': 'ملخص المخاطر',
    'ms.top10Delayed': 'أعلى 10 معالم متأخرة',
    'ms.atRiskByDeptTable': 'المعالم المعرضة للخطر حسب القسم',

    'ms.initiation': 'البدء',
    'ms.initiationDesc': 'جمع المتطلبات واعتماد المشروع',
    'ms.planning': 'التخطيط',
    'ms.planningDesc': 'مرحلة التصميم وتخصيص الموارد',
    'ms.execution': 'التنفيذ',
    'ms.executionDesc': 'مرحلة التطوير والتسليم',
    'ms.monitoring': 'المراقبة',
    'ms.monitoringDesc': 'مرحلة الاختبار والتحقق',
    'ms.closure': 'الإغلاق',
    'ms.closureDesc': 'الإطلاق والتسليم للعمليات',

    'ms.milestoneCol': 'المعلم',
    'ms.projectCol': 'المشروع',
    'ms.stageCol': 'المرحلة',
    'ms.criticalCol': 'حرج',
    'ms.ownerCol': 'المالك',
    'ms.departmentCol': 'القسم',
    'ms.atRiskCol': 'معرض للخطر',
    'ms.criticalPathCol': 'المسار الحرج',
    'ms.pctOfTotalCol': '% من الإجمالي',
    'ms.totalCol': 'الإجمالي',
    'ms.completedCol': 'مكتمل',
    'ms.onTrackCol': 'على المسار',
    'ms.healthPctCol': 'الصحة %',

    'ms.critPathMilestonesAtRisk': 'معالم المسار الحرج المعرضة للخطر',
    'ms.delayedMilestonesLabel': 'المعالم المتأخرة',
    'ms.actionRequired': 'إجراء مطلوب:',
    'ms.actionRequiredText1': 'يلزم اهتمام فوري لـ',
    'ms.actionRequiredText2': 'معالم المسار الحرج لتجنب تأخير المشاريع.',
    'ms.planned': 'المخطط',
    'ms.actual': 'الفعلي',
    'ms.totalCriticalPathLabel': 'إجمالي المسار الحرج',

    'ms.tooltip.totalMilestones': 'عدد جميع المعالم عبر المشاريع النشطة، بما في ذلك المكتملة والتي على المسار والمعرضة للخطر والمتأخرة والقادمة.',
    'ms.tooltip.completed': 'المعالم المكتملة مع توقيع واعتماد جميع المخرجات.',
    'ms.tooltip.onTrack': 'المعالم التي تسير حسب الخطة بدون عوائق، ومتوقع إكمالها بحلول التاريخ المحدد.',
    'ms.tooltip.atRisk': 'المعالم التي تواجه تأخيرات محتملة بسبب التبعيات أو مشكلات الموارد أو تغييرات النطاق.',
    'ms.tooltip.delayed': 'المعالم التي تجاوزت تاريخها المخطط دون اكتمال، وتتطلب إجراءات تصحيحية فورية.',
    'ms.tooltip.upcoming': 'المعالم المجدولة خلال الـ 30 يوماً القادمة والتي لم تبدأ بعد أو في مراحل التخطيط المبكرة.',
    'ms.tooltip.totalCriticalPath': 'المعالم على المسار الحرج حيث أي تأخير يؤثر مباشرة على تاريخ إكمال المشروع.',
    'ms.tooltip.criticalPathOnTrack': 'معالم المسار الحرج التي تسير حسب الجدول بدون مشكلات. أساسية للتسليم في الوقت المحدد.',
    'ms.tooltip.criticalPathAtRisk': 'معالم المسار الحرج المتأخرة أو المعرضة للخطر. تتطلب اهتماماً تنفيذياً فورياً لتجنب تأخير المشاريع.',
    'ms.tooltip.completionRate': 'الصيغة: (المعالم المكتملة / إجمالي المعالم) × 100. يقيس تقدم التسليم على مستوى المحفظة.',
    'ms.tooltip.plannedYTD': 'إجمالي عدد المعالم المخطط إكمالها من 1 يناير حتى التاريخ الحالي هذا العام.',
    'ms.tooltip.actualYTD': 'عدد المعالم المكتملة فعلياً من 1 يناير حتى التاريخ الحالي هذا العام.',
    'ms.tooltip.onTimeDelivery': 'نسبة المعالم المكتملة التي تم تسليمها في أو قبل تاريخها المخطط. أعلى = انضباط تسليم أفضل.',
    'ms.tooltip.avgDelay': 'متوسط عدد الأيام بعد التاريخ المستهدف للمعالم المتأخرة. أقل = قدرة استرداد أفضل.',

    'ms.chart.ragDistDesc': 'رسم دائري يعرض المعالم حسب حالة RAG (أحمر/أصفر/أخضر). يحدد نسبة المعالم المتأخرة والمعرضة للخطر والتي على المسار والمكتملة.',
    'ms.chart.critPathDesc': 'يعرض صحة معالم المسار الحرج. عناصر المسار الحرج تؤثر مباشرة على تاريخ انتهاء المشروع — العناصر المعرضة للخطر تحتاج تصعيداً فورياً.',
    'ms.chart.completionTrendDesc': 'يتتبع المعالم المخططة مقابل المكتملة فعلياً خلال 6 أشهر. الفجوة المتزايدة بين الخطين تشير إلى تأخيرات تسليم متنامية.',
    'ms.chart.completionMetricsDesc': 'مقاييس التسليم الرئيسية: المعالم المخططة مقابل الفعلية حتى الآن، ومعدل الإنجاز الإجمالي مع الاتجاه الشهري.',
    'ms.chart.statusBreakdownDesc': 'عدد المعالم في كل فئة حالة. استخدم هذا لتقييم عدد المعالم التي تحتاج اهتماماً عبر المحفظة بسرعة.',
    'ms.chart.stageDistDesc': 'رسم شريطي مكدس يعرض توزيع حالة المعالم عبر كل مرحلة من مراحل دورة PMO. يساعد في تحديد المراحل ذات أعلى مخاطر التسليم.',
    'ms.chart.stageBreakdownDesc': 'جدول تفصيلي يعرض أعداد المعالم حسب الحالة لكل مرحلة PMO، مع نسبة الصحة المحسوبة من المعالم التي على المسار.',
    'ms.chart.atRiskByDeptDesc': 'رسم شريطي يقارن أعداد المعالم المعرضة للخطر ومعالم المسار الحرج حسب القسم. يحدد الأقسام التي تحمل أعلى مخاطر التسليم.',
    'ms.chart.riskSummaryDesc': 'لوحة مخاطر عالية المستوى تعرض معالم المسار الحرج المعرضة للخطر وإجمالي المعالم المتأخرة التي تتطلب اهتماماً إدارياً فورياً.',
    'ms.chart.top10DelayedDesc': 'يعرض أهم المعالم المتأخرة مع مشروعها ومرحلتها وحالة المسار الحرج والمالك. أعطِ الأولوية لعناصر المسار الحرج أولاً.',
    'ms.chart.atRiskByDeptTableDesc': 'تفصيل على مستوى القسم يعرض أعداد المعرضة للخطر وعناصر المسار الحرج ونسبة إجمالي المعالم المعرضة للخطر لكل قسم.',

    'month.oct': 'أكتوبر',
    'month.nov': 'نوفمبر',
    'month.dec': 'ديسمبر',
    'month.jan': 'يناير',
    'month.feb': 'فبراير',
    'month.mar': 'مارس',

    'portfolio.title': 'تحليل المحفظة المتعمق',
    'portfolio.subtitle': 'ما هي المشاريع الفاشلة ولماذا؟',
    'portfolio.highRisk': 'مشاريع عالية المخاطر',
    'portfolio.openRisks': 'إجمالي المخاطر المفتوحة',
    'portfolio.overAllocated': 'الأدوار المخصصة بشكل زائد',
    'portfolio.milestoneAdherence': 'متوسط الالتزام بالمعالم',
    'portfolio.performanceMatrix': 'مصفوفة أداء المشروع (SPI مقابل CPI)',
    'portfolio.comparisonMatrix': 'مصفوفة مقارنة المشاريع المتعددة',
    'portfolio.riskConcentration': 'تركيز المخاطر (التأثير × الاحتمالية)',
    'portfolio.riskTypeDistribution': 'توزيع أنواع المخاطر',
    'portfolio.resourceUtilization': 'استخدام الموارد حسب الدور',
    'portfolio.milestoneTrend': 'اتجاه الالتزام بالمعالم',
    'portfolio.highRiskTable': 'مشاريع عالية المخاطر (6+ مخاطر مفتوحة)',
    'portfolio.openIssues': 'المشكلات المفتوحة',
    'portfolio.6plusRisks': '6+ مخاطر مفتوحة لكل منها',
    'portfolio.acrossAll': 'عبر جميع المشاريع',
    'portfolio.resourceConstraints': 'قيود الموارد',
    'portfolio.portfolioAvg': 'متوسط المحفظة',
    'portfolio.bubbleSize': 'حجم الفقاعة = الميزانية | اللون = الحالة | الأرباع: أعلى اليمين = أفضل أداء',
    'portfolio.investmentRisk': 'الاستثمار المعرض للخطر: الميزانية مقابل ثقة التسليم | حجم الفقاعة = المخاطر المفتوحة | أسفل اليمين = استثمار عالٍ، ثقة منخفضة',
    'portfolio.lowImpact': 'تأثير منخفض',
    'portfolio.mediumImpact': 'تأثير متوسط',
    'portfolio.highImpact': 'تأثير عالي',
    'portfolio.criticalImpact': 'تأثير حرج',
    'portfolio.highProb': 'عالية',
    'portfolio.mediumProb': 'متوسطة',
    'portfolio.lowProb': 'منخفضة',
    'portfolio.intensity': 'الكثافة:',
    'portfolio.low': 'منخفض',
    'portfolio.medium': 'متوسط',
    'portfolio.high': 'عالي',
    'portfolio.topRight': 'القيم الأعلى في أعلى اليمين = مخاطر أكثر حرجة',
    'portfolio.capacity': 'السعة',
    'portfolio.allocated': 'المخصص',
    'portfolio.overAllocation': 'تنبيهات التخصيص الزائد:',
    'portfolio.overCapacity': 'ساعة فوق السعة',
    'portfolio.plannedMilestones': 'المعالم المخططة',
    'portfolio.achievedMilestones': 'المعالم المحققة',
    'portfolio.forecastAccuracy': 'دقة التوقعات',
    'portfolio.improvingTrend': 'اتجاه متحسن',
    'portfolio.avgDelay': 'متوسط تأخير المعالم',
    'portfolio.days': 'أيام',
    'portfolio.downFrom': 'انخفاضاً من 6.5',
    'portfolio.highRiskZone': 'منطقة عالية المخاطر',
    'portfolio.highRiskDesc': 'الميزانية > 15 مليون دولار، الثقة < 70%',
    'portfolio.avgRiskExposure': 'متوسط التعرض للمخاطر',
    'portfolio.risksPerProject': 'مخاطر/مشروع',
    'portfolio.highConfidence': 'ثقة عالية',
    'portfolio.confidence80': 'الثقة ≥ 80%',
    'portfolio.schedulePerformance': 'مؤشر أداء الجدول الزمني (SPI)',
    'portfolio.costPerformance': 'مؤشر أداء التكلفة (CPI)',
    'portfolio.projectBudget': 'ميزانية المشروع (مليون دولار)',
    'portfolio.deliveryConfidence': 'ثقة التسليم (%)',
    'portfolio.confidenceThreshold': 'عتبة الثقة 70%',

    'pm.title': 'عرض مدير المشروع',
    'pm.subtitle': 'ما الذي يعيقني هذا الأسبوع؟',
    'pm.weeklyFocus': 'التركيز الأسبوعي',
    'pm.schedulePerformance': 'أداء الجدول الزمني (EV مقابل PV)',
    'pm.costPerformance': 'أداء التكلفة',
    'pm.riskRegister': 'سجل المخاطر',
    'pm.issueLog': 'سجل المشكلات',
    'pm.resourceAllocation': 'تخصيص الموارد',
    'pm.tasksOverdue': 'المهام المتأخرة',
    'pm.blockers': 'المعوقات النشطة',
    'pm.teamVelocity': 'سرعة الفريق',
    'pm.sprintProgress': 'تقدم السباق',
    'pm.thisWeek': 'هذا الأسبوع',
    'pm.requiresAction': 'يتطلب إجراء',
    'pm.needsResolution': 'يحتاج إلى حل',
    'pm.pointsPerSprint': 'نقاط/سباق',
    'pm.stable': 'مستقر',
    'pm.completed': 'مكتمل',
    'pm.remaining': 'متبقي',
    'pm.earnedValue': 'القيمة المكتسبة (EV)',
    'pm.plannedValue': 'القيمة المخططة (PV)',
    'pm.actualCost': 'التكلفة الفعلية (AC)',
    'pm.description': 'الوصف',
    'pm.assignee': 'المعين',
    'pm.role': 'الدور',
    'pm.allocation': 'التخصيص',
    'pm.available': 'متاح',
    'pm.overAllocated': 'مخصص بشكل زائد',
    'pm.week': 'الأسبوع',

    'details.title': 'التعمق في تفاصيل المشروع',
    'details.subtitle': 'أين تكمن الاختناقات؟',
    'details.overview': 'نظرة عامة على المشروع',
    'details.taskBreakdown': 'تفصيل المهام حسب المرحلة',
    'details.criticalPath': 'تحليل المسار الحرج',
    'details.burndown': 'مخطط الاحتراق السريع',
    'details.selectProject': 'اختر مشروعاً لعرض التفاصيل',
    'details.name': 'اسم المشروع',
    'details.manager': 'مدير المشروع',
    'details.phase': 'المرحلة الحالية',
    'details.progress': 'التقدم',
    'details.health': 'الصحة',
    'details.totalTasks': 'إجمالي المهام',
    'details.completedTasks': 'المكتملة',
    'details.inProgress': 'قيد التنفيذ',
    'details.blocked': 'محظورة',
    'details.longestTask': 'أطول مهمة على المسار الحرج',
    'details.criticalTasks': 'المهام الحرجة',
    'details.totalDuration': 'المدة الإجمالية',
    'details.atRiskTasks': 'المهام المعرضة للخطر',
    'details.ideal': 'مثالي',
    'details.actual': 'فعلي',
    'details.timeline': 'الجدول الزمني',
    'details.task': 'المهمة',
    'details.duration': 'المدة',
    'details.dependencies': 'التبعيات',
    'details.slack': 'المرونة',
    'details.design': 'التصميم',
    'details.development': 'التطوير',
    'details.testing': 'الاختبار',
    'details.deployment': 'النشر',
    'details.day': 'اليوم',
    'details.tasksRemaining': 'المهام المتبقية',

    'statusBadge.open': 'مفتوح',
    'statusBadge.mitigated': 'تم التخفيف',
    'statusBadge.closed': 'مغلق',
    'common.daysShort': 'ي',
    'common.unknown': 'غير معروف',
    'common.national': 'وطني',
    'common.council': 'مجلس',
    'common.status': 'الحالة',
    'common.budget': 'الميزانية',
    'common.confidence': 'الثقة',
    'common.risks': 'المخاطر',
    'common.issues': 'المشكلات',
    'common.view': 'عرض',
    'common.filters': 'الفلاتر',
    'common.all': 'الكل',
    'common.search': 'البحث عن المشاريع...',
    'common.portfolio': 'المحفظة',
    'common.program': 'البرنامج',
    'common.strategicInitiative': 'المبادرة الاستراتيجية',
    'common.projectManager': 'مدير المشروع',
    'common.spi': 'SPI',
    'common.cpi': 'CPI',
    'common.projects': 'مشاريع',

    'ai.title': 'مساعد PMO الذكي',
    'ai.subtitle': 'مدعوم بتحليلات متقدمة للمحفظة',
    'ai.close': 'إغلاق المساعد',
    'ai.chat': 'محادثة',
    'ai.memory': 'الذاكرة',
    'ai.reports': 'تقارير',
    'ai.placeholder': 'اسأل عن المحفظة...',
    'ai.recentQueries': 'الاستفسارات الأخيرة',
    'ai.autoReports': 'التقارير المُنشأة تلقائياً',
    'ai.generated': 'تم الإنشاء',
    'ai.view': 'عرض',
    'ai.welcome': 'مرحباً! أنا مساعد PMO الذكي. يمكنني مساعدتك في تحليل محفظة المشاريع، تحديد المخاطر، وإنشاء تقارير مخصصة. كيف يمكنني مساعدتك اليوم؟',
  },
};
